export const el = {
    areaLogin: document.getElementById('areaLogin'),
    areaApp: document.getElementById('areaApp'),
    areaUtama: document.getElementById('areaUtama'),
    areaBulanan: document.getElementById('areaBulanan'),
    infoUser: document.getElementById('infoUser'),
    overlayModal: document.getElementById('overlayModal'),
    toastNotification: document.getElementById('toastNotification'),
    daftarItem: document.getElementById('daftarItem'),

    btnLogin: document.getElementById('btnLogin'),
    btnLogout: document.getElementById('btnLogout'),

    teksTanggalHeader: document.getElementById('teksTanggalHeader'),
    wadahNavTanggal: document.getElementById('wadahNavTanggal'),
    btnPrevTanggal: document.getElementById('btnPrevTanggal'),
    btnNextTanggal: document.getElementById('btnNextTanggal'),
    inputTanggal: document.getElementById('inputTanggalPilih'),
    wadahCari: document.getElementById('wadahCari'),
    inputCari: document.getElementById('inputCariItem'),

    btnMenuCatatan: document.getElementById('btnMenuCatatan'),
    btnMenuPengeluaran: document.getElementById('btnMenuPengeluaran'),
    btnMenuAkun: document.getElementById('btnMenuAkun'),
    
    halamanCatatan: document.getElementById('halamanCatatan'),
    halamanPengeluaran: document.getElementById('halamanPengeluaran'),
    halamanAkun: document.getElementById('halamanAkun'),

    btnTambahCatatan: document.getElementById('btnTambahCatatan'),
    wadahInputCatatan: document.getElementById('wadahInputCatatan'),
    inputCatatan: document.getElementById('inputCatatan'),
    btnBatalCatatan: document.getElementById('btnBatalCatatan'),
    btnSimpanCatatan: document.getElementById('btnSimpanCatatan'),
    btnSuaraCatatan: document.getElementById('btnSuaraCatatan'),

    angkaTotalHari: document.getElementById('angkaTotalHari'),
    angkaTotalBulan: document.getElementById('angkaTotalBulan'),
    boxTotalBulan: document.getElementById('boxTotalBulan'),
    btnTambahPengeluaran: document.getElementById('btnTambahPengeluaran'),
    wadahInputPengeluaran: document.getElementById('wadahInputPengeluaran'),
    inputNamaPengeluaran: document.getElementById('inputNamaPengeluaran'),
    inputNominalPengeluaran: document.getElementById('inputNominalPengeluaran'),
    inputKategoriPengeluaran: document.getElementById('inputKategoriPengeluaran'),
    btnBatalPengeluaran: document.getElementById('btnBatalPengeluaran'),
    btnSimpanPengeluaran: document.getElementById('btnSimpanPengeluaran'),
    btnBukaSebulan: document.getElementById('btnBukaSebulan'),

    inputPinMaster: document.getElementById('inputPinMaster'),
    btnTambahAkun: document.getElementById('btnTambahAkun'),
    wadahInputAkun: document.getElementById('wadahInputAkun'),
    inputNamaPlatform: document.getElementById('inputNamaPlatform'),
    inputUsername: document.getElementById('inputUsername'),
    inputPasswordAkun: document.getElementById('inputPasswordAkun'),
    btnBatalAkun: document.getElementById('btnBatalAkun'),
    btnSimpanAkun: document.getElementById('btnSimpanAkun'),

    modalEdit: document.getElementById('modalEdit'),
    inputEditCatatan: document.getElementById('inputEditCatatan'),
    btnBatalEdit: document.getElementById('btnBatalEdit'),
    btnSimpanEdit: document.getElementById('btnSimpanEdit'),
    
    modalEditPengeluaran: document.getElementById('modalEditPengeluaran'),
    inputEditNamaPengeluaran: document.getElementById('inputEditNamaPengeluaran'),
    inputEditNominalPengeluaran: document.getElementById('inputEditNominalPengeluaran'),
    inputEditKategoriPengeluaran: document.getElementById('inputEditKategoriPengeluaran'),
    btnBatalEditPengeluaran: document.getElementById('btnBatalEditPengeluaran'),
    btnSimpanEditPengeluaran: document.getElementById('btnSimpanEditPengeluaran'),

    btnKembali: document.getElementById('btnKembali'),
    judulBulanan: document.getElementById('judulBulanan'),
    btnDownloadPDF: document.getElementById('btnDownloadPDF'),
    inputBulanRekap: document.getElementById('inputBulanRekap'),
    wadahGrafik: document.getElementById('wadahGrafik'),
    grafikPengeluaran: document.getElementById('grafikPengeluaran'),
    grafikKategori: document.getElementById('grafikKategori'),
    kontenBulanan: document.getElementById('kontenBulanan')
};
